# Generated by Django 5.1 on 2024-09-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('id_carteirinha', models.IntegerField()),
                ('id_curso', models.IntegerField()),
                ('nome_curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.IntegerField()),
                ('nome_curso', models.CharField(max_length=20)),
                ('horario_entrada', models.TimeField()),
                ('horario_saida', models.CharField(max_length=20)),
                ('responsavel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aluno', models.IntegerField()),
                ('horario_entrada', models.TimeField()),
                ('horario_saida', models.TimeField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Senai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
                ('endereco', models.CharField(max_length=150)),
                ('telefone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome', models.CharField(max_length=60)),
                ('sobrenome', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=20)),
                ('cargo', models.CharField(choices=[('COORDENAÇÃO', 'Coordenação'), ('ADMINISTRAÇÃO', 'Administração')], max_length=15)),
            ],
        ),
    ]
