# Generated by Django 5.1.1 on 2024-10-10 17:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='id',
            new_name='turma',
        ),
        migrations.RenameField(
            model_name='frequencia',
            old_name='horario_entrada',
            new_name='hora',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='horario_saida',
        ),
        migrations.AddField(
            model_name='curso',
            name='dias_funcionamento',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira')], max_length=3), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='identificador',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome_curso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='responsavel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('COORDENACAO', 'Coordenacao'), ('ADMINISTRAÇÃO', 'Administração')], max_length=15),
        ),
    ]
