# Generated by Django 5.1.1 on 2024-10-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='horario_saida',
            field=models.TimeField(),
        ),
    ]
