# Generated by Django 5.1.1 on 2024-10-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_id_curso_turma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='turma',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
