# Generated by Django 5.1.1 on 2024-10-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_curso_horario_saida'),
        ('web', '0002_alter_frequencia_id'),
    ]

    operations = [
    ]
