# Generated by Django 5.1.1 on 2024-10-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_curso_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='id_carteirinha',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
