# Generated by Django 5.1.1 on 2024-10-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_merge_20241024_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='carga_horaria_intervalo',
            field=models.TimeField(default='02:00:00'),
        ),
        migrations.AddField(
            model_name='curso',
            name='dias_ferias',
            field=models.IntegerField(default='30'),
        ),
    ]
