# Generated by Django 5.1.1 on 2024-11-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_curso_dias_ferias_curso_dias_letivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
