# Generated by Django 5.1.1 on 2024-11-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_usuario_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Senai',
        ),
    ]
