# Generated by Django 5.1.1 on 2024-10-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_id_aluno_frequencia_id_carteirinha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequencia',
            old_name='id_carteirinha',
            new_name='id_aluno',
        ),
    ]
