# Generated by Django 5.1.1 on 2024-10-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_id_carteirinha_frequencia_id_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='data_fim',
            field=models.DateField(default='2024-12-17'),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(default='2024-01-26'),
        ),
    ]
